### ISSUE TITLE
Incorrect CSS selector in ada-embed.md

### ISSUE THREAD

**Issue by jkkealii** [AdaSupport/docs#35]
Under the FAQ section of the `ada-embed.md` doc, the answer to:

> Q: How do I customize the look of the Ada Chat button?

says

> ...we recommend targetting the `button.ada-chat-button` element in your CSS

however, this should be `button.ada-embed-button`, as it says in the following example that is provided:

**Example:**

```
// This line in your CSS
button.ada-embed-button {
  // This will make the chat button appear larger
  width: 60px !important;
  height: 60px !important;
}
```

**Comment by NicHaley** [comment]
Thanks @jkkealii ! Good catch.

As a heads up, this a feature that we are looking to modify our approach to customization, as selecting any DOM elements is inhernetly rigid and prone to breaking as we develop new features. I will update the docs for the time being though.
