### ISSUE TITLE
Having troubles with adaEmbed.start()

### ISSUE THREAD

**Issue by ashleyongym** [AdaSupport/docs#36]
I'm trying to use this function `adaEmbed.start()`, since I'm using `data-lazy`.

Example:
``` 
<script
  async
  id="__ada"
  data-handle="ada-example"
  data-lazy
  src="https://static.ada.support/embed.js"
></script>
```

From the documentation, it says I can pass in an optional object into `adaEmbed.start()`.
<img width="887" alt="Screenshot 2020-03-18 at 3 29 11 PM" src="https://user-images.githubusercontent.com/32433646/76936459-f4d0f080-692d-11ea-9215-93d886b06e20.png">

So I ran `adaEmbed.start()`, but my console says:-
```
Uncaught TypeError: Cannot read property 'parentElement' of undefined
```
Right now, if I add in the parentElement, I don't get the button widget anymore. 

Could you help me? Am I missing something?

**Comment by NicHaley** [comment]
When using `adaEmbed.start({ ... })` you need to pass all the info you would normally pass into `window.adaSettings`, as well as the bot handle.

So you code should be :

`adaEmbed.start({
  handle: "my-handle",
  language: "fr",
  mobileOverlay: true
`
