### ISSUE TITLE
Feedback: GIF outdated

### ISSUE THREAD

**Issue by perri-maxwell** [AdaSupport/docs#8]
Update GIF to include our new Ada logo in our docs

**Comment by noqcks** [comment]
where is the logo specifically?

**Comment by perri-maxwell** [comment]
In the GIF under Chaperone, at the top of the doc :)

**Comment by noqcks** [comment]
adding new gif here for reference.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4740147/47372740-5b5dca80-d6b8-11e8-87e7-1b76d48370d8.gif)
